### ISSUE TITLE
Add Service Workers

### ISSUE THREAD

**Issue by fgruchala** [GDG-Lille/meet-a-winner#9]

**Comment by fgruchala** [comment]
@Gillespie59 : tu as déjà mis en place les service worker avec Angular ? J'ai lu et suivi le Getting Started mais il n'a pas l'air d'inclure mon worker et encore moins générer le registrer ...

**Comment by Gillespie59** [comment]
Ah merde. Je viens de voir ton message. 
C'est toujours d'actu ?

**Comment by fgruchala** [comment]
Nan nan, tkt, je suis en refonte dessus 😁

Le jeu. 22 nov. 2018 à 16:49, Emmanuel DEMEY <notifications@github.com> a
écrit :

**Comment by Gillespie59** [comment]
On clos alors ?

**Comment by fgruchala** [comment]
Ouep, fais toi plaiz.

François GRUCHALA
/ http://linkedin.gruchala.me
/ http://twitter.gruchala.me
/ tel:+33677264684
<ois.gruchala@gmail.com>
